version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=password_checker_db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5435:5432"
